In [71]:
import pypsa, pandas as pd

n = pypsa.Network("../resources/networks/base_s_50__168H-T-H-B-I-A-dist1_2035_NT_0.0.nc")
s = pd.Timestamp("2024-12-09 00:00:00")

bus = "BE0 0 rural heat"

n.loads_t.p_set.loc[s, bus]

INFO:pypsa.io:Imported network base_s_50__168H-T-H-B-I-A-dist1_2035_NT_0.0.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores

867.5390825182947

In [93]:
bs = pd.Index(n.buses.location.unique())
bs = bs.drop(['', 'EU'])

In [73]:
n.loads.loc[n.loads.bus == 'BA0 0 rural heat']

,bus,carrier,type,p_set,q_set,sign,active
Load,,,,,,,
BA0 0 agriculture heat,BA0 0 rural heat,agriculture heat,,4.970925,0.0,-1.0,True
BA0 0 rural heat,BA0 0 rural heat,rural heat,,0.000000,0.0,-1.0,True

In [74]:
n.links.loc['BA0 0 rural air heat pump', 'p_max_pu']

1.0

In [106]:
rh = n.loads_t.p_set[bs + ' rural heat']
rh.columns = bs

ah = n.loads.loc[bs + ' agriculture heat', 'p_set']
ah.index = bs

loads = rh.add(ah, axis=1)

loads.head()

,AL0 0,AT0 0,BA0 0,BE0 0,BG0 0,CH0 0,CZ0 0,DE0 0,DE0 1,DE0 2,...,NL0 0,NO1 0,PL0 0,PT0 0,RO0 0,RS0 0,SE1 0,SI0 0,SK0 0,XK0 0
snapshot,,,,,,,,,,,,,,,,,,,,,
2024-01-01,222.949141,5401.604710,942.623091,1403.314619,807.529964,1828.125746,3802.827869,5659.391443,4769.303727,2984.270831,...,4983.754463,2412.364387,20668.919695,2865.764978,4726.169436,1771.029907,3663.697179,859.159616,1813.805842,26.696809
2024-01-08,378.184454,7553.666360,2020.404708,1973.351912,1401.466849,2467.915361,5985.357492,7696.495355,8073.975726,4550.428464,...,5692.209515,1718.540617,26457.481189,3171.504206,8222.055592,3648.354951,2425.979203,1369.603937,2934.593858,26.696809
2024-01-15,260.685251,6967.471536,1430.565904,1935.688900,1055.729514,2294.884972,5256.780804,7114.622929,7485.679576,4397.189387,...,5589.944109,2346.992862,23064.774439,2032.784314,6539.598546,2603.869780,3537.369007,1217.031539,2508.281107,26.696809
2024-01-22,372.537158,5242.485860,1520.310446,1364.774396,1190.984031,1548.993279,3863.587660,4565.582791,4688.192732,2795.099237,...,4855.079512,1480.325595,17503.053669,1653.421589,6695.015503,2624.689602,2358.667587,1102.900346,2136.820135,26.696809
2024-01-29,356.812656,5076.042559,1421.391719,1324.728948,1109.462204,1608.674841,3848.695284,4422.245495,4482.862313,2678.320904,...,4789.927695,1464.858760,16688.425614,1876.242787,6316.588827,2511.783710,2176.147063,1055.542279,2071.077957,26.696809

In [114]:
ss = (bs + ' rural gas boiler').intersection(n.links_t.p_set.columns)
pset = n.links_t.p_set.loc[:, ss]
pset.columns = list(map(lambda x: ' '.join(x.split()[:2]), pset.columns))

In [119]:
(pset < loads[pset.columns]).all().all()

True

In [77]:
inter = n.links_t.p_max_pu.columns.intersection(n.links_t.p_set.columns)
inter

Index(['AT0 0 rural gas boiler', 'BE0 0 rural gas boiler',
       'BG0 0 rural gas boiler', 'CZ0 0 rural gas boiler',
       'DE0 0 rural gas boiler', 'DE0 1 rural gas boiler',
       'DE0 2 rural gas boiler', 'DE0 3 rural gas boiler',
       'DE0 4 rural gas boiler', 'DE0 5 rural gas boiler',
       'DK0 0 rural gas boiler', 'DK1 0 rural gas boiler',
       'EE0 0 rural gas boiler', 'ES0 0 rural gas boiler',
       'ES6 0 rural gas boiler', 'FR0 0 rural gas boiler',
       'FR0 1 rural gas boiler', 'FR0 2 rural gas boiler',
       'FR0 3 rural gas boiler', 'FR0 4 rural gas boiler',
       'GR0 0 rural gas boiler', 'HR0 0 rural gas boiler',
       'HU0 0 rural gas boiler', 'IE3 0 rural gas boiler',
       'IT0 0 rural gas boiler', 'IT0 1 rural gas boiler',
       'IT4 0 rural gas boiler', 'LU0 0 rural gas boiler',
       'LV0 0 rural gas boiler', 'NL0 0 rural gas boiler',
       'PL0 0 rural gas boiler', 'PT0 0 rural gas boiler',
       'RO0 0 rural gas boiler', 'SE1 0 rural gas boiler',
       'SI0 0 rural gas boiler', 'SK0 0 rural gas boiler',
       'AT0 0 urban decentral gas boiler', 'BE0 0 urban decentral gas boiler',
       'BG0 0 urban decentral gas boiler', 'CZ0 0 urban decentral gas boiler',
       'DE0 0 urban decentral gas boiler', 'DE0 1 urban decentral gas boiler',
       'DE0 2 urban decentral gas boiler', 'DE0 3 urban decentral gas boiler',
       'DE0 4 urban decentral gas boiler', 'DE0 5 urban decentral gas boiler',
       'DK0 0 urban decentral gas boiler', 'DK1 0 urban decentral gas boiler',
       'EE0 0 urban decentral gas boiler', 'ES0 0 urban decentral gas boiler',
       'ES6 0 urban decentral gas boiler', 'FR0 0 urban decentral gas boiler',
       'FR0 1 urban decentral gas boiler', 'FR0 2 urban decentral gas boiler',
       'FR0 3 urban decentral gas boiler', 'FR0 4 urban decentral gas boiler',
       'GR0 0 urban decentral gas boiler', 'HR0 0 urban decentral gas boiler',
       'HU0 0 urban decentral gas boiler', 'IE3 0 urban decentral gas boiler',
       'IT0 0 urban decentral gas boiler', 'IT0 1 urban decentral gas boiler',
       'IT4 0 urban decentral gas boiler', 'LU0 0 urban decentral gas boiler',
       'LV0 0 urban decentral gas boiler', 'NL0 0 urban decentral gas boiler',
       'PL0 0 urban decentral gas boiler', 'PT0 0 urban decentral gas boiler',
       'RO0 0 urban decentral gas boiler', 'SE1 0 urban decentral gas boiler',
       'SI0 0 urban decentral gas boiler', 'SK0 0 urban decentral gas boiler'],
      dtype='object', name='Link')

In [80]:
pset = n.links_t.p_set.loc[:, inter]
mul = n.links_t.p_max_pu.loc[:, inter].mul(n.links.p_nom.loc[inter], axis=1)

In [67]:
n.snapshots

DatetimeIndex(['2024-01-01', '2024-01-08', '2024-01-15', '2024-01-22',
               '2024-01-29', '2024-02-05', '2024-02-12', '2024-02-19',
               '2024-02-26', '2024-03-04', '2024-03-11', '2024-03-18',
               '2024-03-25', '2024-04-01', '2024-04-08', '2024-04-15',
               '2024-04-22', '2024-04-29', '2024-05-06', '2024-05-13',
               '2024-05-20', '2024-05-27', '2024-06-03', '2024-06-10',
               '2024-06-17', '2024-06-24', '2024-07-01', '2024-07-08',
               '2024-07-15', '2024-07-22', '2024-07-29', '2024-08-05',
               '2024-08-12', '2024-08-19', '2024-08-26', '2024-09-02',
               '2024-09-09', '2024-09-16', '2024-09-23', '2024-09-30',
               '2024-10-07', '2024-10-14', '2024-10-21', '2024-10-28',
               '2024-11-04', '2024-11-11', '2024-11-18', '2024-11-25',
               '2024-12-02', '2024-12-09', '2024-12-16', '2024-12-23',
               '2024-12-30'],
              dtype='datetime64[ns]', name='snapshot', freq=None)

In [68]:
n.links_t.p_set.columns[n.links_t.p_set.columns.str.contains('BG0 0')]

Index(['BG0 0 urban central gas boiler', 'BG0 0 rural gas boiler',
       'BG0 0 urban decentral gas boiler'],
      dtype='object', name='Link')

In [69]:
n.loads.carrier.unique()

array(['electricity', 'land transport EV', 'land transport oil',
       'urban central heat', 'heat100-200 industry',
       'heat200-500 industry', 'heat>500 industry',
       'solid biomass for industry', 'gas for industry',
       'H2 for industry', 'industry methanol', 'naphtha for industry',
       'low-temperature heat for industry', 'industry electricity',
       'process emissions', 'NH3', 'coal for industry',
       'shipping methanol', 'shipping oil', 'kerosene for aviation',
       'agriculture electricity', 'agriculture heat',
       'agriculture machinery electric', 'agriculture machinery oil',
       'rural heat', 'urban decentral heat'], dtype=object)

In [70]:
# bus = 'BA0 0'
bus = 'AT0 0'

names = [
    f'{bus} rural gas boiler',
    ]

# n.links_t.p_set[n.links_t.p_set.columns[n.links_t.p_set.columns.str.contains('rural')]]
n.links_t.p_set[names]

Link        AT0 0 rural gas boiler
snapshot
2024-01-01              312.060193
2024-01-08              436.388574
2024-01-15              402.523070
2024-01-22              302.867617
2024-01-29              293.251895
2024-02-05              230.271343
2024-02-12              252.431761
2024-02-19              271.530218
2024-02-26              246.786645
2024-03-04              263.826553
2024-03-11              222.391391
2024-03-18              234.496435
2024-03-25              193.639900
2024-04-01              147.178961
2024-04-08              120.535392
2024-04-15              261.914864
2024-04-22              249.246984
2024-04-29              118.238513
2024-05-06              122.010555
2024-05-13              115.994932
2024-05-20              109.583265
2024-05-27              119.376153
2024-06-03               77.831603
2024-06-10              115.725079
2024-06-17               65.895172
2024-06-24               63.358914
2024-07-01               80.260600
2024-07-08               60.136447
2024-07-15               59.016202
2024-07-22               60.636109
2024-07-29               60.033963
2024-08-05               58.583261
2024-08-12               58.227881
2024-08-19               62.329186
2024-08-26               60.410801
2024-09-02               63.664429
2024-09-09              176.280656
2024-09-16              134.066194
2024-09-23              128.827776
2024-09-30              196.408606
2024-10-07              150.865688
2024-10-14              147.443822
2024-10-21              141.070423
2024-10-28              179.462582
2024-11-04              263.147587
2024-11-11              316.250464
2024-11-18              330.654620
2024-11-25              313.341881
2024-12-02              339.226195
2024-12-09              359.203206
2024-12-16              306.457940
2024-12-23              370.238702
2024-12-30              389.634661

In [15]:
n.links.carrier.value_counts()

carrier
gas pipeline                          254
DC                                    134
CO2 pipeline                          116
electricity distribution grid         100
shipping oil                           50
solid biomass for industry             50
solid biomass for industry CC          50
gas for industry                       50
gas for industry CC                    50
methanolisation                        50
Fischer-Tropsch                        50
naphtha for industry                   50
HVC to air                             50
process emissions                      50
process emissions CC                   50
agriculture machinery oil              50
kerosene for aviation                  50
co2 sequestered                        50
home battery charger                   50
home battery discharger                50
rural air heat pump                    50
rural biomass boiler                   50
rural gas boiler                       50
rural ground heat pump                 50
urban decentral air heat pump          50
urban decentral biomass boiler         50
OCGT methanol                          50
biomass-to-methanol                    50
ammonia cracker                        50
Haber-Bosch                            50
OCGT                                   50
CCGT                                   50
H2 Electrolysis                        50
battery charger                        50
battery discharger                     50
Sabatier                               50
SMR CC                                 50
SMR                                    50
BEV charger                            50
V2G                                    50
land transport oil                     50
urban decentral gas boiler             50
unsustainable bioliquids               50
biogas to gas                          50
biomass to liquid                      50
electrobiofuels                        50
urban central air heat pump            49
urban central gas boiler               49
urban central gas CHP                  49
urban central gas CHP CC               49
urban central solid biomass CHP        49
urban central solid biomass CHP CC     49
gas pipeline new                       31
coal for industry                       1
oil refining                            1
industry methanol                       1
shipping methanol                       1
Name: count, dtype: int64

In [ ]:
# 1) What is creating the RHS demand at that bus?
print("Loads at bus:")
print(n.loads[n.loads.bus == bus])

print("\nLoad p_set at snapshot (nonzero only):")
if not n.loads_t.p_set.empty:
    cols = n.loads[n.loads.bus == bus].index
    for col in cols:
        if col in n.loads_t.p_set.columns:
            val = n.loads_t.p_set.loc[s, col]
        else:
            val = n.loads.loc[col, 'p_set']
        if abs(val) > 1e-6:
            print(f"{col}: {val}")

# 2) Check the links in the IIS: do they have p_set defined (=forcing dispatch)?
links = [
    "BA0 0 rural air heat pump",
    "BA0 0 rural biomass boiler",
    "BA0 0 rural gas boiler",
    "BA0 0 rural ground heat pump",
]
print("\nLink p_set at snapshot:")
print(n.links.p_set.loc[links])
print(n.links_t.p_set.columns.intersection(links))
print(n.links_t.p_set.loc[s, links])

print("\nLink meta:")
print(n.links.loc[links, ["bus0","bus1","efficiency","p_nom","p_nom_extendable","p_min_pu","p_max_pu"]])

# 3) Generators in the IIS: why is p <= 0?
gens = ["BA0 0 rural heat vent", "BA0 0 rural solar thermal collector"]
print("\nGenerator meta:")
print(n.generators.loc[gens, ["bus","p_nom","p_nom_extendable"]])

print("\nGenerator p_max_pu at snapshot (if exists):")
if not n.generators_t.p_max_pu.empty:
    print(n.generators_t.p_max_pu.loc[s, gens])