In [32]:
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import pypsa

sys.path.append(str(Path.cwd().parent / 'scripts'))
from _tyndp_helpers import _extract_scenario_values, _extract_scenario_values_rowwise

In [33]:
year = 2035
scenario = 'GA'

In [34]:
valpath = Path.cwd().parent / 'data' / 'TYNDP_2024-Scenario-Report-Data-Figures_240522.xlsx'

In [35]:
scenario_mapper = {
    'NT': 'National Trends',
    'DE': 'Distributed Energy',
    'GA': 'Global Ambition',
    'REF': 'Reference',
}

In [36]:
# prenetwork
# n = pypsa.Network(Path.cwd().parent / 'resources' / 'networks' / 'base_s_50__168H-T-H-B-I-A-dist1_{}.nc'.format(year))
n = pypsa.Network(Path.cwd().parent / 'results' / 'networks' / 'base_s_50__168H-T-H-B-I-A-dist1_{}.nc'.format(year))

INFO:pypsa.io:Imported network base_s_50__168H-T-H-B-I-A-dist1_2035.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores

In [37]:
eu27_countries = [
    "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", "DE", "GR", "HU",
    "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PL", "PT", "RO", "SK", "SI", "ES", "SE",
]
eu27_buses = n.buses.index[
    (n.buses.country.isin(eu27_countries)) &
    (n.buses.carrier == 'AC')
]
all_eu27_buses = n.buses.index[
    (n.buses.country.isin(eu27_countries))
]

In [38]:
# adjust EV demand
def final_electricity_transport(path):
    return _extract_scenario_values(path, sheet_name='6-', row_label='Transport')
ev_demand = final_electricity_transport(valpath)

In [39]:
ev_demand

{'National Trends': {2030: 247.64143184472053, 2040: 488.45309616768986},
 'Distributed Energy': {2040: 616.8067207371424, 2050: 849.9178634898052},
 'Global Ambition': {2040: 533.8023438415136, 2050: 779.9316227533446},
 'Reference': {2019: 50.09668955008888}}

In [40]:
weight = (year - 2030) / (2040 - 2030)

tyndp_p_set = ev_demand['National Trends'][2030] * (1 - weight) + ev_demand[scenario_mapper[scenario]][2040] * weight

In [41]:
n.loads.carrier.unique()

array(['electricity', 'land transport EV', 'land transport oil',
       'urban central heat', 'solid biomass for industry',
       'gas for industry', 'H2 for industry', 'industry methanol',
       'naphtha for industry', 'low-temperature heat for industry',
       'industry electricity', 'process emissions', 'NH3',
       'coal for industry', 'shipping methanol', 'shipping oil',
       'kerosene for aviation', 'agriculture electricity',
       'agriculture heat', 'agriculture machinery electric',
       'agriculture machinery oil', 'rural heat', 'urban decentral heat'],
      dtype=object)

In [ ]:
tyndp_p_set

390.72188784311703

In [56]:
idx = pd.IndexSlice
eb = n.statistics.energy_balance().loc[idx[:,:,'urban central heat']].sort_values()
eb = eb.loc[eb > 0]

In [93]:
def to_ac_bus(x):
    return ' '.join(x.split(' ')[:2])

In [ ]:
uc = pd.Index(n.loads.loc[n.loads.carrier == 'urban central heat', 'bus'])
lt = pd.Index(n.loads.loc[n.loads.carrier == 'low-temperature heat for industry', 'bus'])
inter = uc.intersection(lt)
inter = inter.map(to_ac_bus)

Index(['AL0 0', 'AT0 0', 'BA0 0', 'BE0 0', 'BG0 0', 'CH0 0', 'CZ0 0', 'DE0 0',
       'DE0 1', 'DE0 2', 'DE0 3', 'DE0 4', 'DE0 5', 'DK0 0', 'DK1 0', 'EE0 0',
       'ES0 0', 'ES6 0', 'FI1 0', 'FR0 0', 'FR0 1', 'FR0 2', 'FR0 3', 'FR0 4',
       'GB2 0', 'GB2 1', 'GB3 0', 'GR0 0', 'HR0 0', 'HU0 0', 'IE3 0', 'IT0 0',
       'IT0 1', 'IT4 0', 'LT0 0', 'LU0 0', 'LV0 0', 'ME0 0', 'MK0 0', 'NL0 0',
       'NO1 0', 'PL0 0', 'PT0 0', 'RO0 0', 'RS0 0', 'SE1 0', 'SI0 0', 'SK0 0',
       'XK0 0'],
      dtype='object', name='bus')

In [101]:
urban_central_load = (
    n.loads_t
    .p_set[inter + ' urban central heat']
    .add(
        n.loads.loc[
            inter + ' low-temperature heat for industry',
            'p_set'
        ].to_list(), axis=1
    )
)
urban_central_load.head()

Load,AL0 0 urban central heat,AT0 0 urban central heat,BA0 0 urban central heat,BE0 0 urban central heat,BG0 0 urban central heat,CH0 0 urban central heat,CZ0 0 urban central heat,DE0 0 urban central heat,DE0 1 urban central heat,DE0 2 urban central heat,...,NL0 0 urban central heat,NO1 0 urban central heat,PL0 0 urban central heat,PT0 0 urban central heat,RO0 0 urban central heat,RS0 0 urban central heat,SE1 0 urban central heat,SI0 0 urban central heat,SK0 0 urban central heat,XK0 0 urban central heat
snapshot,,,,,,,,,,,,,,,,,,,,,
2024-01-01,102.337371,3317.906403,379.109535,4157.538804,948.170613,2361.599666,4326.822886,5804.102535,1514.458559,9504.194662,...,6975.355667,3967.655878,13692.505717,1582.635372,2330.242924,1380.607329,14305.332059,460.425930,1146.491057,17.866889
2024-01-08,171.047584,4644.255315,792.569289,7499.436565,1721.044785,3132.157962,6897.555770,7877.550211,2527.751234,15394.269623,...,10607.119158,2881.746396,18030.123377,1748.428167,4038.059122,2786.752243,8870.904140,722.988408,1845.034107,17.866889
2024-01-15,119.040118,4282.974369,566.294687,7278.633580,1271.146044,2923.761329,6039.388243,7285.296659,2347.365350,14817.961319,...,10082.874512,3865.342348,15487.822543,1130.936083,3216.142369,2004.417017,13750.665034,644.508180,1579.330151,17.866889
2024-01-22,168.547979,3219.838992,600.722585,3931.593090,1447.149128,2025.414406,4398.389930,4690.779354,1489.587958,8792.749758,...,6315.727386,2508.914039,11320.186377,925.219575,3292.066923,2020.011380,8575.360141,585.801348,1347.813150,17.866889
2024-01-29,161.588004,3117.257409,562.775276,3696.822848,1341.066956,2097.294476,4380.848669,4544.884792,1426.628666,8353.564635,...,5981.738674,2484.706764,10709.750599,1046.048523,3107.197286,1935.443155,7773.970285,561.441294,1306.838639,17.866889

In [102]:
p_max_pu = urban_central_load.div(urban_central_load.max(), axis=1)
p_max_pu.head()

Load,AL0 0 urban central heat,AT0 0 urban central heat,BA0 0 urban central heat,BE0 0 urban central heat,BG0 0 urban central heat,CH0 0 urban central heat,CZ0 0 urban central heat,DE0 0 urban central heat,DE0 1 urban central heat,DE0 2 urban central heat,...,NL0 0 urban central heat,NO1 0 urban central heat,PL0 0 urban central heat,PT0 0 urban central heat,RO0 0 urban central heat,RS0 0 urban central heat,SE1 0 urban central heat,SI0 0 urban central heat,SK0 0 urban central heat,XK0 0 urban central heat
snapshot,,,,,,,,,,,,,,,,,,,,,
2024-01-01,0.598298,0.714411,0.478330,0.554380,0.550927,0.753985,0.627298,0.736790,0.599133,0.617385,...,0.657611,1.000000,0.759424,0.726365,0.577070,0.495418,1.000000,0.636837,0.621393,1.0
2024-01-08,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,0.726310,1.000000,0.802457,1.000000,1.000000,0.620112,1.000000,1.000000,1.0
2024-01-15,0.695947,0.922209,0.714505,0.970557,0.738590,0.933465,0.875584,0.924818,0.928638,0.962563,...,0.950576,0.974213,0.858997,0.519054,0.796457,0.719266,0.961227,0.891450,0.855990,1.0
2024-01-22,0.985386,0.693295,0.757943,0.524252,0.840855,0.646651,0.637674,0.595462,0.589294,0.571170,...,0.595423,0.632342,0.627849,0.424638,0.815260,0.724862,0.599452,0.810250,0.730509,1.0
2024-01-29,0.944696,0.671207,0.710064,0.492947,0.779217,0.669600,0.635131,0.576941,0.564386,0.542641,...,0.563936,0.626240,0.593992,0.480094,0.769478,0.694516,0.543432,0.776556,0.708301,1.0

In [ ]:
urban_central_load.head()

Load,AL0 0 urban central heat,AT0 0 urban central heat,BA0 0 urban central heat,BE0 0 urban central heat,BG0 0 urban central heat,CH0 0 urban central heat,CZ0 0 urban central heat,DE0 0 urban central heat,DE0 1 urban central heat,DE0 2 urban central heat,...,NL0 0 urban central heat,NO1 0 urban central heat,PL0 0 urban central heat,PT0 0 urban central heat,RO0 0 urban central heat,RS0 0 urban central heat,SE1 0 urban central heat,SI0 0 urban central heat,SK0 0 urban central heat,XK0 0 urban central heat
snapshot,,,,,,,,,,,,,,,,,,,,,
2024-01-01,102.337371,3317.906403,379.109535,4157.538804,948.170613,2361.599666,4326.822886,5804.102535,1514.458559,9504.194662,...,6975.355667,3967.655878,13692.505717,1582.635372,2330.242924,1380.607329,14305.332059,460.425930,1146.491057,17.866889
2024-01-08,171.047584,4644.255315,792.569289,7499.436565,1721.044785,3132.157962,6897.555770,7877.550211,2527.751234,15394.269623,...,10607.119158,2881.746396,18030.123377,1748.428167,4038.059122,2786.752243,8870.904140,722.988408,1845.034107,17.866889
2024-01-15,119.040118,4282.974369,566.294687,7278.633580,1271.146044,2923.761329,6039.388243,7285.296659,2347.365350,14817.961319,...,10082.874512,3865.342348,15487.822543,1130.936083,3216.142369,2004.417017,13750.665034,644.508180,1579.330151,17.866889
2024-01-22,168.547979,3219.838992,600.722585,3931.593090,1447.149128,2025.414406,4398.389930,4690.779354,1489.587958,8792.749758,...,6315.727386,2508.914039,11320.186377,925.219575,3292.066923,2020.011380,8575.360141,585.801348,1347.813150,17.866889
2024-01-29,161.588004,3117.257409,562.775276,3696.822848,1341.066956,2097.294476,4380.848669,4544.884792,1426.628666,8353.564635,...,5981.738674,2484.706764,10709.750599,1046.048523,3107.197286,1935.443155,7773.970285,561.441294,1306.838639,17.866889

In [155]:
eff = 1.035
w = n.snapshot_weightings['generators'].iloc[0]
target_generation = 200_000_000

# cap * p_max_pu.mean() * w * len(n.shapshots) / eff
cap = target_generation * eff / (p_max_pu.mean() * w * len(n.snapshots))
# cap * p_max_pu

In [ ]:
existing = pd.read_csv(Path.cwd().parent / 'resources' / 'existing_heating_distribution_base_s_50_2030.csv', header=[0, 1], index_col=0)
idx = pd.IndexSlice

res = existing.loc[:, idx['residential urban decentral', :]]
res.columns = res.columns.get_level_values(1)
ser = existing.loc[:, idx['services urban decentral', :]]
ser.columns = ser.columns.get_level_values(1)

existing = (res + ser)['gas boiler']

In [156]:
target_distribution = target_generation * existing / existing.sum()

In [1]:
n.links.loc[n.links.carrier == 'urban central gas boiler']

NameError: name 'n' is not defined

In [ ]:
capacities = pd.Series(index=existing.index, name='capacity')

for bus in existing.index:

    current_trajectory = (existing.loc[bus] * p_max_pu[bus + ' urban central heat'] / eff).sum() * w

    factor = target_distribution.loc[bus] / current_trajectory
    print(np.round(factor, 3))

    p_set = p_max_pu[bus + ' urban central heat'] * factor * existing.loc[bus]
    p_nom = p_set.max()

    # print('target', target_distribution.loc[bus])
    # print(p_set.sum() * w / eff)

AL0 0
nan
AT0 0
0.089
BA0 0
nan
BE0 0
0.113
BG0 0
0.104
CH0 0
nan
CZ0 0
0.101
DE0 0
0.098
DE0 1
0.103
DE0 2
0.1
DE0 3
0.102
DE0 4
0.105
DE0 5
0.097
DK0 0
0.095
DK1 0
0.094
EE0 0
0.133
ES0 0
0.102
ES6 0
0.168
FI1 0
nan
FR0 0
0.125
FR0 1
0.098
FR0 2
0.118
FR0 3
0.133
FR0 4
0.106
FR5 0

/tmp/ipykernel_656236/1324279592.py:8: RuntimeWarning: invalid value encountered in scalar divide
  factor = target_distribution.loc[bus] / current_trajectory

KeyError: 'FR5 0 urban central heat'

Load,AL0 0 urban central heat,AT0 0 urban central heat,BA0 0 urban central heat,BE0 0 urban central heat,BG0 0 urban central heat,CH0 0 urban central heat,CZ0 0 urban central heat,DE0 0 urban central heat,DE0 1 urban central heat,DE0 2 urban central heat,...,NL0 0 urban central heat,NO1 0 urban central heat,PL0 0 urban central heat,PT0 0 urban central heat,RO0 0 urban central heat,RS0 0 urban central heat,SE1 0 urban central heat,SI0 0 urban central heat,SK0 0 urban central heat,XK0 0 urban central heat
snapshot,,,,,,,,,,,,,,,,,,,,,
2024-01-01,3244.141031,3771.884913,3389.833638,3711.345442,3392.685925,3526.469510,3742.236311,4268.580378,3633.459581,3660.277561,...,3815.233007,4818.359507,4777.753360,4854.801606,3550.060686,3594.395227,5724.287285,3596.784126,3771.296192,2324.797844
2024-01-08,5422.285906,5279.713900,7086.812094,6694.585674,6158.136879,4677.109211,5965.643694,5793.480741,6064.531702,5928.676934,...,5801.658446,3499.620575,6291.286951,5363.378085,6151.871458,7255.277263,3549.697663,5647.886145,6069.101070,2324.797844
2024-01-15,3773.625669,4869.000039,5063.562377,6497.479600,4548.336801,4365.919985,5223.421105,5357.912645,5631.753391,5706.727739,...,5514.918160,4694.108972,5404.196845,3469.194743,4899.704004,5218.476543,5502.336940,5034.809376,5195.087871,2324.797844
2024-01-22,5343.047303,3660.399253,5371.401770,3509.648565,5178.100237,3024.459331,3804.134105,3449.795828,3573.790519,3386.284244,...,3454.443434,3046.849370,3949.975236,2838.150568,5015.372963,5259.076286,3431.435553,4576.199670,4433.530092,2324.797844
2024-01-29,5122.412940,3543.781760,5032.093326,3300.074220,4798.523519,3131.794575,3788.962802,3342.498849,3422.739807,3217.144248,...,3271.765329,3017.451822,3736.974661,3208.798525,4733.729180,5038.903890,3110.758917,4385.902273,4298.747515,2324.797844
2024-02-05,3100.254432,2779.966608,2654.420714,2920.363569,2275.429130,2973.326976,2831.457463,3562.493736,2954.837837,2988.867508,...,3213.406145,4547.382535,3631.533973,3507.237344,2383.165645,2393.741043,4957.028486,2763.230403,2690.836694,2324.797844
2024-02-12,3884.064117,3048.723587,3701.118960,2714.857945,3639.262400,2778.715702,3047.361831,2869.670435,2776.064935,2710.921559,...,2744.512627,3683.686216,3287.494738,2131.664544,3561.232391,3814.033039,4104.052446,3286.606590,3475.479674,2324.797844
2024-02-19,3237.695638,3280.345740,3284.581738,3475.818712,3083.362037,3241.968550,3134.106017,3200.342965,3203.183535,3250.845375,...,3328.586948,2966.790790,3133.386872,3200.617516,3162.035763,3004.766805,3249.047350,3165.660035,3159.657622,2324.797844
2024-02-26,2688.283590,2980.260780,2465.215827,3758.603259,2937.233814,3049.721263,2910.991463,3613.313185,3375.297659,3357.332028,...,3504.693382,2776.768850,2649.949621,5023.270205,2678.998677,2138.338702,2962.322699,2948.665262,2340.909290,2324.797844
2024-03-04,3521.531328,3186.917275,3208.155993,3493.160094,3502.513876,3321.257011,3274.017052,3853.493133,3509.601056,3472.383279,...,3607.525012,3025.593013,3871.841783,4694.742644,3400.418871,2991.566219,3326.081137,3283.759379,3214.002805,2324.797844
2024-03-11,3096.569658,2684.400175,2874.537533,2557.665571,2954.880702,2774.067398,2605.433368,2784.624136,2748.694518,2675.555288,...,2681.627396,3227.902067,3089.800874,2394.850572,3048.408264,2631.155149,3381.129362,2649.255156,2716.695411,2324.797844
2024-03-18,3012.487240,2831.207646,3030.672026,2625.029028,3168.490720,2568.781678,3086.093326,2975.821224,2889.642595,2665.190823,...,2770.234336,2968.110418,3502.682449,1373.298599,3317.110785,3114.754287,3158.990318,2683.029775,3223.960646,2324.797844
2024-03-25,1971.862732,2335.708019,1804.749379,2829.676297,1876.394910,2806.865785,2043.571526,2666.283548,2530.897717,2691.168371,...,2802.126946,3113.582856,1927.352883,4555.657265,1916.658465,1637.069963,3137.595426,2194.133509,1994.679053,2324.797844
2024-04-01,1601.534536,1772.239324,1225.720340,1597.102693,1194.941354,2130.039296,1470.152867,1884.032385,1659.555783,1763.088895,...,1835.944310,3385.301235,1579.359807,2036.917343,1376.916975,928.827050,3564.216878,1563.594935,1369.086751,2324.797844
2024-04-08,1089.042107,1449.111612,664.937769,1438.287496,1111.711103,1889.245311,1271.850017,1470.025354,1354.135585,1478.182243,...,1581.962210,2322.106358,1100.475456,1812.780079,916.469895,672.123967,2127.588473,978.946474,924.918373,2324.797844
2024-04-15,2580.421531,3163.732705,3011.930577,3686.696715,1975.500838,3224.411415,3284.594024,3404.593879,3391.946755,3507.742084,...,3433.356425,2966.068579,3333.274522,1154.278095,2250.117938,2641.669111,3117.669747,2946.728815,2916.305545,2324.797844
2024-04-22,2317.443774,3010.099271,2615.347699,3227.670931,1708.742881,3210.928567,2817.253283,3065.843682,3024.984456,3052.854714,...,3143.429180,2693.138059,2724.364356,2577.572941,2024.616316,2072.541767,2861.593772,3140.164430,2619.860344,2324.797844
2024-04-29,1493.949861,1421.255540,918.915899,1390.766739,1466.019864,1920.631528,900.042546,1062.876064,1087.081437,1323.895471,...,1415.739412,1883.387314,709.908184,2909.811092,1011.978371,913.713115,1744.733738,1229.180585,716.363423,2324.797844
2024-05-06,1268.388643,1467.002080,853.375988,1104.813774,1320.324552,1756.368354,1340.125002,1319.916756,1304.454765,1175.704569,...,1298.493395,2046.437237,1582.381829,1221.854933,1240.620944,851.939322,2092.441693,1062.950776,1079.370773,2324.797844
2024-05-13,1231.672798,1394.045844,767.356161,878.804379,1475.598000,1760.893140,1013.913668,825.694399,936.315323,946.592122,...,919.899395,1351.932766,850.655721,2092.105918,1389.858323,879.271976,892.469361,1084.940808,1106.516130,2324.797844
2024-05-20,1062.322866,1316.286476,651.746807,845.739765,947.447377,1780.208159,837.215658,818.260181,826.533854,939.537139,...,932.301577,1277.606680,699.788655,1466.028010,830.661881,637.512762,927.670104,929.518251,677.486829,2324.797844
2024-05-27,1099.333393,1435.052604,574.467228,1128.823586,997.895327,1749.773180,878.055799,875.248210,898.235170,1025.216884,...,1043.235061,1039.134870,699.530251,1080.538179,905.675191,628.952764,561.931329,938.891831,671.356366,2324.797844
2024-06-03,1009.542925,931.208860,547.036302,1024.440916,904.447432,1076.789089,828.932154,1190.375068,874.396408,1159.274267,...,1324.576566,1478.115289,729.414402,1073.964526,780.241061,593.928621,1045.258371,802.478957,663.083085,2324.797844
2024-06-10,1008.705661,1390.773130,547.551674,1388.021226,905.189818,1514.009113,1051.698164,1383.059536,1194.010406,1441.867136,...,1459.735745,1348.752436,897.675583,1110.582089,797.985359,595.294073,1077.266787,1046.668816,848.141086,2324.797844
2024-06-17,1008.652049,786.446285,529.670805,638.278566,904.447432,1023.963623,779.700152,832.630403,746.202077,836.132015,...,914.891561,1149.002299,698.143222,1124.239943,776.239157,593.532186,807.364814,783.486832,634.915249,2324.797844
2024-06-24,1008.652049,755.687069,529.670805,622.895979,904.918969,833.197997,779.683365,813.817713,740.401888,822.712188,...,902.240654,905.189867,696.924470,1073.833072,776.239157,593.532186,615.417034,783.501602,635.139863,2324.797844
2024-07-01,1009.326475,960.667231,544.516301,774.662043,905.249911,1109.112075,827.155810,951.142288,917.936679,1003.942098,...,971.328334,1218.844801,705.345038,1075.327273,805.569262,596.170391,856.896289,785.884077,657.792342,2324.797844
2024-07-08,1008.652049,716.605660,529.670805,685.621103,904.447432,801.491899,779.683365,813.874514,740.401888,840.526797,...,936.213435,954.548170,696.912120,1073.852636,776.239157,593.532186,637.720466,783.486832,634.915249,2324.797844
2024-07-15,1008.652049,703.019557,529.670805,622.895979,904.447432,704.736834,779.683365,813.817713,740.401888,822.712188,...,902.240654,726.649070,696.912120,1073.779129,776.239157,593.532186,519.965820,783.486832,634.915249,2324.797844
2024-07-22,1008.652049,722.665451,529.670805,622.895979,904.447432,686.277987,779.683365,813.817713,740.401888,822.712188,...,902.240654,825.741018,697.054142,1073.779129,777.922500,593.532186,551.712622,783.486832,636.942072,2324.797844
2024-07-29,1008.652049,715.362758,529.670805,622.895979,904.447432,682.291658,779.795872,813.817713,740.401888,822.712188,...,902.240654,860.146086,697.744740,1073.779129,779.199090,593.532186,627.249878,783.486832,648.183973,2324.797844
2024-08-05,1008.652049,697.768941,529.670805,622.895979,904.447432,665.025317,779.964778,813.817713,740.401888,822.712188,...,902.240654,816.297035,697.493136,1073.779129,781.572688,593.532186,573.146103,783.486832,641.630691,2324.797844
2024-08-12,1008.652049,693.458957,529.670805,622.895979,904.447432,723.979955,779.683365,813.817713,740.401888,822.712188,...,902.240654,906.576790,696.912120,1073.779129,776.239157,593.532186,655.069557,783.486832,634.915249,2324.797844
2024-08-19,1008.652049,743.198748,529.670805,643.928578,904.686350,793.491981,781.274471,813.817713,740.539737,829.641303,...,902.240654,1088.128559,698.401221,1073.779129,776.252680,593.532186,764.653158,783.486832,636.973013,2324.797844
2024-08-26,1008.652049,719.932971,529.670805,632.324060,905.470971,735.596156,780.639354,818.184093,741.821647,829.657203,...,902.240654,1147.891108,697.208285,1073.779129,776.239157,593.532186,843.954660,783.486832,634.915249,2324.797844
2024-09-02,1008.652049,759.392290,529.670805,622.895979,904.482875,923.233656,779.683365,813.817713,740.401888,822.712188,...,902.240654,851.877022,696.912120,1159.954755,782.783220,593.532186,653.557378,783.758667,634.915249,2324.797844
2024-09-09,1230.876194,2125.178688,1339.412187,1761.712217,1001.399607,2114.898085,1677.677179,1671.681519,1694.499815,1836.577992,...,1696.742773,1384.788904,902.903586,1076.097685,984.806729,1116.809895,1205.645030,1518.370946,1076.858819,2324.797844
2024-09-16,1277.121377,1613.210385,1166.937422,663.368021,1076.639632,1749.550678,952.628462,840.715765,893.505790,858.359066,...,903.553054,1441.504484,748.255369,1084.696664,1082.342961,970.393099,1317.099068,1237.482539,953.364632,2324.797844
2024-09-23,1048.847986,1549.679930,820.830967,1480.442926,958.546632,1883.591021,1312.191829,1356.601075,1372.032971,1495.878230,...,1462.190180,2178.426616,1029.484585,1298.397187,904.459790,775.151357,1904.230225,1092.576955,1043.223690,2324.797844
2024-09-30,1484.843141,2369.286305,1644.677926,2155.102493,1302.819705,2250.627256,2353.206217,2375.417906,2278.213677,2340.127049,...,2304.039180,2247.968811,2295.516301,1075.716739,1548.203789,1485.967500,2235.952470,2151.450050,2214.022742,2324.797844
2024-10-07,1321.500566,1816.951189,1007.759401,1863.706037,1160.395119,1924.461727,1833.015394,1948.282184,1822.814249,1910.743155,...,1906.128906,2355.789983,1714.278230,1201.555430,1348.176930,1076.394132,2216.225130,1379.306772,1631.223585,2324.797844
2024-10-14,1411.336317,1775.451504,1188.639088,1255.698723,2349.095273,1654.515178,2259.458079,1899.240162,1928.751127,1671.198311,...,1591.432051,2065.976019,2548.003421,1237.988759,2739.756026,1867.330969,2051.581224,1833.948180,2824.904386,2324.797844
2024-10-21,1694.012981,1698.156233,1286.234171,1515.431469,2536.960818,1748.991579,1958.493708,1843.894262,1878.495185,1765.081313,...,1766.955659,2024.886025,2222.050421,2005.517433,2521.105468,1930.135990,1891.384547,1502.394053,2270.752424,2324.797844
2024-10-28,1923.730666,2163.768428,2092.419635,2074.030499,1971.923839,2121.175453,2372.812650,2249.306871,2230.822010,2216.761308,...,2170.282893,2685.450685,2261.594736,1462.466709,2158.587400,2064.844314,2676.434811,1981.829915,2479.804510,2324.797844
2024-11-04,3070.876883,3178.682910,4039.876114,3438.293247,3931.295419,2515.331021,3724.758251,3531.791312,3720.247540,3564.018829,...,3601.851352,2407.823435,3941.560229,1301.770431,3906.429380,4359.130877,2453.963270,3705.776074,4046.581792,2324.797844
2024-11-11,3703.270531,3822.703661,4956.144361,3253.722267,4230.825325,3351.961711,4044.994134,3044.423874,3580.486313,3205.277932,...,2904.583259,2518.639198,3964.244349,2368.965952,4410.857214,5158.756785,2589.727156,4469.857140,4562.797755,2324.797844
2024-11-18,3584.930401,3997.394295,4813.729017,4194.027060,4127.212065,3836.536973,4111.165603,4285.088906,4064.910888,4129.422270,...,4138.390227,3604.561263,4316.998229,1912.913439,4369.624906,4884.253985,3776.208668,4238.310461,4520.552463,2324.797844
2024-11-25,3897.858718,3787.428961,4062.489420,3884.093579,4063.665536,3560.775260,3838.549833,3612.557360,3648.726425,3574.324227,...,3604.634021,3046.549697,3619.565154,2661.135110,4056.919976,4238.158285,3315.049104,3430.791762,4106.799930,2324.797844
2024-12-02,3876.511718,4101.348591,5020.716949,3769.854352,4097.086127,3652.629565,4244.711669,3800.762948,4070.434777,3747.222722,...,3551.639281,3262.773456,4204.454526,3281.505465,4346.227960,4872.338808,3552.993184,4613.117294,4571.030488,2324.797844
2024-12-09,4179.695789,4343.625663,5086.104171,4856.091985,4075.663040,4209.994415,4579.571627,4337.791162,4675.918448,4495.490755,...,4286.656347,3394.640058,4649.778132,6480.282119,4525.716420,4890.742590,3634.471746,4731.761582,4727.549999,2324.797844
2024-12-16,4466.017638,3703.941950,5059.519874,3478.913886,4000.308311,3719.366386,3475.268424,3091.115984,3368.088668,3305.242645,...,3191.949276,3514.107186,3207.066621,4698.761818,4060.717260,4835.932397,3868.215930,4273.442309,4035.427850,2324.797844
2024-12-23,4842.707230,4477.461882,5933.911434,4785.237692,4869.476933,4459.672872,4714.049759,4267.954710,4758.404307,4489.115635,...,4240.501734,2950.625738,4531.556075,5207.066188,4608.941545,5759.840920,3101.064969,4741.195823,4808.247192,2324.797844
2024-12-30,4915.028884,4712.692078,5978.446596,5249.996859,5083.861739,4524.053268,5203.839021,4093.050396,5292.073485,4985.229067,...,4050.751865,3500.694518,4519.954007,6683.691579,4936.768174,6295.750425,3709.727570,4968.161651,5498.517372,2324.797844

In [ ]:
(cap * eff * p_max_pu * w).sum().sum() =

In [ ]:
energy_shares = eb / eb.sum()
energy_shares.round(2)

component  carrier
Link       Sabatier                              0.00
           Fischer-Tropsch                       0.00
           urban central gas CHP CC              0.00
           urban central solid biomass CHP CC    0.00
Generator  urban central solar thermal           0.00
Link       H2 Electrolysis                       0.00
           methanolisation                       0.01
           Haber-Bosch                           0.02
           urban central gas CHP                 0.07
           urban central gas boiler              0.25
           urban central solid biomass CHP       0.28
           urban central air heat pump           0.37
dtype: float64

In [ ]:
gas_boiler_target = 200 # TWh

In [ ]:

capacity_factor = n.loads

In [55]:
n.links.loc[n.links.carrier == 'urban central gas boiler']

,bus0,bus1,type,carrier,efficiency,active,build_year,lifetime,p_nom,p_nom_mod,...,tags,location,dc,project_status,under_construction,geometry,reversed,underground,length_original,voltage
Link,,,,,,,,,,,,,,,,,,,,,
AL0 0 urban central gas boiler,AL0 0 gas,AL0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
AT0 0 urban central gas boiler,AT0 0 gas,AT0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
BA0 0 urban central gas boiler,BA0 0 gas,BA0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
BE0 0 urban central gas boiler,BE0 0 gas,BE0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
BG0 0 urban central gas boiler,BG0 0 gas,BG0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
CH0 0 urban central gas boiler,CH0 0 gas,CH0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
CZ0 0 urban central gas boiler,CZ0 0 gas,CZ0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
DE0 0 urban central gas boiler,DE0 0 gas,DE0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
DE0 1 urban central gas boiler,DE0 1 gas,DE0 1 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
DE0 2 urban central gas boiler,DE0 2 gas,DE0 2 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
DE0 3 urban central gas boiler,DE0 3 gas,DE0 3 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
DE0 4 urban central gas boiler,DE0 4 gas,DE0 4 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
DE0 5 urban central gas boiler,DE0 5 gas,DE0 5 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
DK0 0 urban central gas boiler,DK0 0 gas,DK0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
DK1 0 urban central gas boiler,DK1 0 gas,DK1 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
EE0 0 urban central gas boiler,EE0 0 gas,EE0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
ES0 0 urban central gas boiler,ES0 0 gas,ES0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
ES6 0 urban central gas boiler,ES6 0 gas,ES6 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
FI1 0 urban central gas boiler,FI1 0 gas,FI1 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
FR0 0 urban central gas boiler,FR0 0 gas,FR0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
FR0 1 urban central gas boiler,FR0 1 gas,FR0 1 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
FR0 2 urban central gas boiler,FR0 2 gas,FR0 2 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
FR0 3 urban central gas boiler,FR0 3 gas,FR0 3 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
FR0 4 urban central gas boiler,FR0 4 gas,FR0 4 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
GB2 0 urban central gas boiler,GB2 0 gas,GB2 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
GB2 1 urban central gas boiler,GB2 1 gas,GB2 1 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
GB3 0 urban central gas boiler,GB3 0 gas,GB3 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
GR0 0 urban central gas boiler,GR0 0 gas,GR0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
HR0 0 urban central gas boiler,HR0 0 gas,HR0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
HU0 0 urban central gas boiler,HU0 0 gas,HU0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
IE3 0 urban central gas boiler,IE3 0 gas,IE3 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
IT0 0 urban central gas boiler,IT0 0 gas,IT0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
IT0 1 urban central gas boiler,IT0 1 gas,IT0 1 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
IT4 0 urban central gas boiler,IT4 0 gas,IT4 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
LT0 0 urban central gas boiler,LT0 0 gas,LT0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
LU0 0 urban central gas boiler,LU0 0 gas,LU0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
LV0 0 urban central gas boiler,LV0 0 gas,LV0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
ME0 0 urban central gas boiler,ME0 0 gas,ME0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
MK0 0 urban central gas boiler,MK0 0 gas,MK0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
NL0 0 urban central gas boiler,NL0 0 gas,NL0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
NO1 0 urban central gas boiler,NO1 0 gas,NO1 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
PL0 0 urban central gas boiler,PL0 0 gas,PL0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
PT0 0 urban central gas boiler,PT0 0 gas,PT0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
RO0 0 urban central gas boiler,RO0 0 gas,RO0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
RS0 0 urban central gas boiler,RS0 0 gas,RS0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
SE1 0 urban central gas boiler,SE1 0 gas,SE1 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
SI0 0 urban central gas boiler,SI0 0 gas,SI0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
SK0 0 urban central gas boiler,SK0 0 gas,SK0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN
XK0 0 urban central gas boiler,XK0 0 gas,XK0 0 urban central heat,,urban central gas boiler,1.035,True,0,25.0,0.0,0.0,...,,,NaN,,NaN,,False,NaN,0.0,NaN

In [22]:
n = pypsa.Network(Path.cwd().parent / 'resources' / 'networks' / 'base_s_50__168H-T-H-B-I-A-dist1_{}.nc'.format(year))

loads = n.loads.index[
    (n.loads.carrier == 'land transport EV') &
    (n.loads.index.str.contains('|'.join(eu27_countries)))
]
w = n.snapshot_weightings['generators'].iloc[0]

print('before')
print(n.loads_t.p_set[loads].sum().sum() * w * 1e-6)

factor = tyndp_p_set * 1e6 / (n.loads_t.p_set[loads].sum().sum() * w)
n.loads_t.p_set[loads] *= factor

print('after')
print(n.loads_t.p_set[loads].sum().sum() * w * 1e-6)

INFO:pypsa.io:Imported network base_s_50__168H-T-H-B-I-A-dist1_2035.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores

before
380.99519180496895
after
390.7218878431169

In [23]:
eudh_buses = n.buses.index[
    (n.buses.carrier == 'urban central heat') &
    (n.buses.index.str.contains('|'.join(eu27_countries)))
]

In [14]:
eudh_buses

Index(['AT0 0 urban central heat', 'BE0 0 urban central heat',
       'BG0 0 urban central heat', 'CZ0 0 urban central heat',
       'DE0 0 urban central heat', 'DE0 1 urban central heat',
       'DE0 2 urban central heat', 'DE0 3 urban central heat',
       'DE0 4 urban central heat', 'DE0 5 urban central heat',
       'DK0 0 urban central heat', 'DK1 0 urban central heat',
       'EE0 0 urban central heat', 'ES0 0 urban central heat',
       'ES6 0 urban central heat', 'FI1 0 urban central heat',
       'FR0 0 urban central heat', 'FR0 1 urban central heat',
       'FR0 2 urban central heat', 'FR0 3 urban central heat',
       'FR0 4 urban central heat', 'GR0 0 urban central heat',
       'HR0 0 urban central heat', 'HU0 0 urban central heat',
       'IE3 0 urban central heat', 'IT0 0 urban central heat',
       'IT0 1 urban central heat', 'IT4 0 urban central heat',
       'LT0 0 urban central heat', 'LU0 0 urban central heat',
       'LV0 0 urban central heat', 'NL0 0 urban central heat',
       'PL0 0 urban central heat', 'PT0 0 urban central heat',
       'RO0 0 urban central heat', 'SE1 0 urban central heat',
       'SI0 0 urban central heat', 'SK0 0 urban central heat'],
      dtype='object', name='Bus')

In [ ]:
dh_links = n.links.index[
    (n.links.bus0.isin(eudh_buses)) |
    (n.links.bus1.isin(eudh_buses)) 
]

In [ ]:
n = pypsa.Network(Path.cwd().parent / 'resources' / 'networks' / 'base_s_50__168H-T-H-B-I-A-dist1_{}.nc'.format(year))